on:
    workflow_dispatch:
    schedule:
        - cron: '*/5 * * * *'

jobs:
    run-integration:
        runs-on: ubuntu-latest

        steps:
            - name: Run Launchdarkly Integration
              uses: port-labs/ocean-sail@v1
              with:
                type: gcp
                identifier: my-gcp-integration
                port_client_id: ${{ secrets.PORT_CLIENT_ID }}
                port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
                config: |
                    encoded_adc_configuration: ${{ secrets.ENCODED_ADC_CONFIGURATION }}
