name: BDC Debugging
run-name: ${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      name_demo:
        description: Name Demo
        required: true
        type: string
      run_id:
        description: Run ID
        required: true
        type: string
jobs:
  acknowledge_incident:
    runs-on: ubuntu-latest
    steps:
      - name: Log After Upserting Entity
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{inputs.run_id}}
          logMessage: "Entity upserting was successful ✅"
